### ISSUE TITLE
create_aihub fails to run

### ISSUE THREAD

**Issue by rmthurman** [microsoft/Build-your-own-AI-Assistant-Solution-Accelerator#6]
When attempting to run the create_aihub script I get this error:

    {
      "code": "DeploymentScriptError",
      "message": "azure-cli 2.52.0 requires azure-mgmt-resource==23.1.0b2, but you have azure-mgmt-resource 22.0.0 which is incompatible."
    },
    {
      "code": "DeploymentScriptError",
      "message": "azure-cli-core 2.52.0 requires msal[broker]==1.24.0b1, but you have msal 1.28.0 which is incompatible."

**Comment by megangavin** [comment]
Thank you for your feedback @rmthurman. Our team will review and respond to your logged issue. Your patience is appreciated.

**Comment by pd-illinois** [comment]
+1 I see same issue. Was there any solution for this?

**Comment by megangavin** [comment]
@rmthurman and @pd-illinois - Updates have been made and deployment completed successfully. Please retry deployment yourself.
